[tox]
env_list = py311, py312, py313, lint
skip_missing_interpreters = true

[testenv]
package = editable
extras = dev
commands =
    pytest

[testenv:lint]
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files
